# .github/workflows/sync-from-main.yml
name: Sync From Main Repository

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-from-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout child repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history needed

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install git-filter-repo

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Extract regex_patterns with history
        run: |
          # Clone the main repository with the stable branch
          git clone -b stable https://github.com/Dictionarry-Hub/database.git main-repo

          # Create a temporary directory for the filtered repository
          mkdir -p filtered-repo
          cd filtered-repo
          git init

          # Add the main repo as a remote
          git remote add origin ../main-repo

          # Fetch the stable branch specifically
          git fetch origin stable

          # Create a local stable branch tracking the remote stable branch
          git checkout -b stable origin/stable

          # Use git-filter-repo to keep only the regex_patterns directory
          git-filter-repo --path regex_patterns --force

          # Now filtered-repo has only the regex_patterns folder with full history
          cd ..

      - name: Create temp branch for changes
        run: |
          # Create a temporary branch for our changes
          TEMP_BRANCH="sync-$(date +%s)"
          git checkout -b ${TEMP_BRANCH}

      - name: Apply regex_patterns changes with history
        run: |
          # Remove existing regex_patterns if it exists
          rm -rf regex_patterns

          # Copy regex_patterns from filtered repo
          cp -r filtered-repo/regex_patterns ./

          # Add regex_patterns changes
          git add regex_patterns
          git commit -m "Update regex_patterns from main repo (stable branch)" || echo "No changes to regex_patterns"

      - name: Update profiles and custom_formats folders
        run: |
          # Ensure directories exist
          mkdir -p profiles custom_formats

          # Create .gitkeep files
          touch profiles/.gitkeep
          touch custom_formats/.gitkeep

          # Remove all other files from these directories
          find profiles -type f ! -name ".gitkeep" -delete
          find profiles -type d -mindepth 1 -delete  # Remove all subdirectories
          find custom_formats -type f ! -name ".gitkeep" -delete
          find custom_formats -type d -mindepth 1 -delete  # Remove all subdirectories

          # Add these changes
          git add profiles custom_formats
          git commit -m "Update profiles and custom_formats to only include .gitkeep" || echo "No changes to .gitkeep files"

      - name: Push changes
        run: |
          # Check what branches exist and their commits
          git branch -v

          # Print current branch state
          echo "Temp branch commits:"
          git log --oneline ${TEMP_BRANCH} -n 5

          echo "Main branch commits:"
          git log --oneline main -n 5

          # Try to merge with --allow-unrelated-histories flag
          git checkout main
          git merge --allow-unrelated-histories ${TEMP_BRANCH} -m "Merge sync changes from Dictionarry-Hub/database"
          git push origin main

          # Clean up
          git branch -D ${TEMP_BRANCH} || echo "No temp branch to delete"
          rm -rf main-repo filtered-repo
