name: Sync Database Repository

on:
  schedule:
    # Runs at 00:00 and 12:00 UTC every day
    - cron: "0 0,12 * * *"
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  sync-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: current-repo

      - name: Clone source repository
        uses: actions/checkout@v3
        with:
          repository: Dictionarry-Hub/database
          path: source-repo
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Sync regex_patterns folder and create additional folders
        run: |
          # Create directories if they don't exist
          mkdir -p current-repo/regex_patterns
          mkdir -p current-repo/custom_formats
          mkdir -p current-repo/profiles

          # Add .gitkeep files to empty directories
          touch current-repo/custom_formats/.gitkeep
          touch current-repo/profiles/.gitkeep

          # Get the last processed commit hash if available
          LAST_COMMIT_FILE="current-repo/.last_processed_commit"
          if [ -f "$LAST_COMMIT_FILE" ]; then
            LAST_COMMIT=$(cat "$LAST_COMMIT_FILE")
          else
            # If no previous commit was processed, get the earliest commit
            LAST_COMMIT=$(cd source-repo && git rev-list --max-parents=0 HEAD)
          fi

          # Get the current commit hash
          CURRENT_COMMIT=$(cd source-repo && git rev-parse HEAD)

          # Get all commits since the last processed commit that affected regex_patterns
          COMMIT_LOG=$(cd source-repo && git log --pretty=format:"- %s (%an)" $LAST_COMMIT..$CURRENT_COMMIT -- regex_patterns)

          # If there are no commits affecting regex_patterns, use a default message
          if [ -z "$COMMIT_LOG" ]; then
            COMMIT_MSG="Sync regex_patterns and maintain custom directories"
          else
            COMMIT_MSG="Sync regex_patterns with changes:\n\n$COMMIT_LOG"
          fi

          # Copy regex_patterns from source to current repo
          cp -r source-repo/regex_patterns/* current-repo/regex_patterns/

          # Save the current commit hash for next run
          echo "$CURRENT_COMMIT" > current-repo/.last_processed_commit

          # Navigate to the current repo
          cd current-repo

          # Add all changes
          git add regex_patterns custom_formats profiles .last_processed_commit

          # Commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "$COMMIT_MSG"
            git push
          fi
