# .github/workflows/sync-from-main.yml
name: Sync From Main Repository

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch: # Allows manual triggering

jobs:
  mixed-sync-approach:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout child repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history needed

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install git-filter-repo

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Extract regex_patterns with history
        run: |
          # Clone the main repository
          git clone --mirror https://github.com/Dictionarry-Hub/database.git temp-main

          # Create a temporary directory for the filtered repository
          mkdir -p filtered-regex
          cd filtered-regex
          git init

          # Push the main repo content to our filtered repo
          cd ../temp-main
          git push --mirror ../filtered-regex

          # Go to filtered repo and extract only the regex_patterns folder
          cd ../filtered-regex
          git-filter-repo --path regex_patterns --force

          # Now filtered-regex has only the regex_patterns folder with full history
          cd ..

      - name: Create temp branch
        run: |
          TEMP_BRANCH="sync-$(date +%s)"
          git checkout -b ${TEMP_BRANCH}

      - name: Apply regex_patterns changes with history
        run: |
          # Remove existing regex_patterns if it exists
          rm -rf regex_patterns

          # Extract regex_patterns from filtered repo
          cp -r filtered-regex/regex_patterns ./

          # Add regex_patterns changes
          git add regex_patterns
          git commit -m "Update regex_patterns with history from main repo" || echo "No changes to regex_patterns"

      - name: Update profiles and custom_formats folders
        run: |
          # Ensure directories exist
          mkdir -p profiles custom_formats

          # Create .gitkeep files
          touch profiles/.gitkeep
          touch custom_formats/.gitkeep

          # Remove all other files from these directories
          find profiles -type f ! -name ".gitkeep" -delete
          find custom_formats -type f ! -name ".gitkeep" -delete

          # Add these changes
          git add profiles custom_formats
          git commit -m "Update profiles and custom_formats to only include .gitkeep" || echo "No changes to .gitkeep files"

      - name: Push changes
        run: |
          # Only push if there are commits in the temp branch
          if git rev-parse --verify ${TEMP_BRANCH} >/dev/null 2>&1; then
            git checkout main
            git merge --no-ff ${TEMP_BRANCH} -m "Merge sync changes from Dictionarry-Hub/database"
            git push origin main
          else
            echo "No changes to push"
          fi

          # Clean up
          git branch -D ${TEMP_BRANCH} || echo "No temp branch to delete"
          rm -rf temp-main filtered-regex
